version: '3.8'

services:
  database:
    image: postgres:16
    container_name: con-storerader-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_NAME}"
    networks:
      - network

  backend:
    image: ha2yo/storerader-backend
    container_name: con-storerader-back
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://con-storerader-db:5432/${DB_NAME}"
      - "SPRING_DATASOURCE_USERNAME=${DB_USER}"
      - "SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}"
      - "SPRING_JPA_HIBERNATE_DDL_AUTO=none"
      - "SPRING_FLYWAY_ENABLED=true"
    networks:
      - network

  frontend:
    image: ha2yo/storerader-frontend
    container_name: con-storerader-front
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - network



networks:
  network: