name: CD
on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy: 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # (1) GET GitHub IP
    - name: get GitHub IP 
      id: ip
      uses: haythem/public-ip@v1.2
          
    # (2) Configure AWS Credentials - AWS 접근 권한 취득(IAM)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    # (3) Add github ip to AWS Security Group
    - name: Add GitHub IP to AWS
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

    # (4) Copy docker-compose.yml
    - name: Copy docker-compose.yml to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        source: "docker-compose.yml"
        target: "~/StoreRader-java"
        
    # (5) AWS EC2 Server Connect & Deploy
    - name: AWS EC2 Connection
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        timeout: 60s
        script: |
          set -e
          cd ~/StoreRader-java

          echo "DB_NAME=${{ secrets.DB_NAME }}" > .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" >> .env

          sudo docker-compose pull
          sudo docker-compose up -d --remove-orphans
          
          sudo docker image prune -f
        
    # (6) REMOVE Github IP FROM security group
    - name: Remove IP FROM security group
      if: always()
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
