name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./backend
        
    # (1) Spring Boot 어플리케이션 Build
    - name: Spring Boot Build
      run: ./gradlew clean build --exclude-task test
      working-directory: ./backend

    # (2) DockerHub Login
    - name: DockerHub login 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # (3) Docker image build
    - name: Build Backend & Frontend image
      run: | 
        docker build -t ha2yo/storerader-backend ./backend
        docker build \
          --build-arg VITE_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
          --build-arg VITE_GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }} \
          --build-arg VITE_API_SERVER_URL=${{ secrets.API_SERVER_URL }} \
          -t ha2yo/storerader-frontend ./frontend

    # (4) Docker Hub push
    - name: docker Hub push
      run: |
        docker push ha2yo/storerader-backend
        docker push ha2yo/storerader-frontend