name: CI & CD

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-push: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ./backend
        
    # (1-1) Spring Boot Build
    - name: Spring Boot Build
      run: ./gradlew clean build --exclude-task test
      working-directory: ./backend

    # (1-2) DockerHub Login
    - name: DockerHub login 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # (1-3) Docker image build
    - name: Build Backend & Frontend image
      run: | 
        docker build -t ha2yo/storerader-backend ./backend
        docker build \
          --build-arg VITE_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
          --build-arg VITE_GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }} \
          --build-arg VITE_API_SERVER_URL=${{ secrets.API_SERVER_URL }} \
          -t ha2yo/storerader-frontend ./frontend

    # (1-4) Docker Hub push
    - name: docker Hub push
      run: |
        docker push ha2yo/storerader-backend
        docker push ha2yo/storerader-frontend
  
  deploy: 
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # (2-1) Get GitHub IP
    - name: get GitHub IP 
      id: ip
      uses: haythem/public-ip@v1.2
          
    # (2-2) Configure AWS Credentials - AWS 접근 권한 취득(IAM)
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2
        
    # (2-3) Add github ip to AWS Security Group
    - name: Add GitHub IP to AWS
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

    # (2-4) Copy docker-compose.yml
    - name: Copy docker-compose.yml to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        source: "docker-compose.yml"
        target: "~/StoreRader-java"
        
    # (2-5) AWS EC2 Server Connect & Deploy
    - name: AWS EC2 Connection
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.EC2_SSH_PORT }}
        timeout: 60s
        script: |
          set -e
          cd ~/StoreRader-java

          echo "DB_NAME=${{ secrets.DB_NAME }}" > .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD='${{ secrets.DB_PASSWORD }}'" >> .env
          echo "VITE_GOOGLE_CLIENT_ID='${{ secrets.VITE_GOOGLE_CLIENT_ID }}'" >> .env

          sudo docker-compose pull
          sudo docker-compose up -d --remove-orphans
          
          sudo docker image prune -f
        
    # (2-6) REMOVE Github IP FROM security group
    - name: Remove IP FROM security group
      if: always()
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
